# Yaml doesn't like tabs, use only spaces for indentation
database:
    driver: mysql
    host: localhost
    database: test
    password:
    username: root
    charset: utf8
    collation: utf8_unicode_ci

